### ISSUE TITLE
[ARV-66] 마이페이지 수요조사 API 구현

### ISSUE THREAD

**Issue by tnals2384** [prgrms-web-devcourse-final-project/WEB1_1_Allreva_BE#54]
### 👥 팀 선택 (Team)

BE

### 🏷️ 라벨 선택 (Label)

FEAT

### 🎟️ 상위 작업 (Ticket Number)

ARV-31

### 🌳 브랜치명 (Branch)

feat/mypage-survey

### 📝 상세 내용(Description)

마이페이지의 수요조사 API를 구현합니다.

### ✅ 체크리스트(Tasks)

- [ ] 내 수요조사 관리
- [ ] 내가 참여중인 수요조사

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement API endpoints for managing user's surveys in the mypage, including listing user's created surveys and participated surveys.

You can review changes in this commit: https://github.com/jjyutm4532/prgrms-web-devcourse-final-project-WEB1_1_Allreva_BE-54/commit/46e0af87c30276c403be3b35f74ad5734ff1c54d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
